[build]
builder = "NIXPACKS"
buildCommand = "npm --prefix backend install && npm --prefix backend run build"

[deploy]
startCommand = "npm --prefix backend start"
healthcheckPath = "/api/health"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
